-- Initial schema for the food-order demo (H2-compatible).
-- NOTE: intentionally NO seed data here. Demo/seed products are added later
-- as a separate V2__ migration (see PLANUNG.md sections 3 and 6).

CREATE TABLE products (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price_cents INT          NOT NULL,
    category    VARCHAR(100) NOT NULL
);

CREATE TABLE orders (
    id            BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    status        VARCHAR(30)              NOT NULL,
    total_cents   BIGINT                   NOT NULL,
    customer_name VARCHAR(255)             NOT NULL
);

CREATE TABLE order_items (
    id               BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    quantity         INT    NOT NULL,
    unit_price_cents BIGINT NOT NULL,
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_order_items_order_id   ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
