-- Demo/seed products for the food-order demo (intentionally omitted from V1).
-- IDs are assigned by H2 (products.id is GENERATED BY DEFAULT AS IDENTITY), so no id column here.
-- Prices are integer cents (e.g. 149 = 1.49 EUR). File encoding: UTF-8.

INSERT INTO products (name, description, price_cents, category) VALUES
    ('Bio-Äpfel 1 kg',         'Knackige Äpfel aus regionalem Bio-Anbau, lose.',         299, 'Obst & Gemüse'),
    ('Bananen 1 kg',           'Süße Fairtrade-Bananen, ideal für den Snack.',           189, 'Obst & Gemüse'),
    ('Bauernbrot 750 g',       'Kräftiges Roggenmischbrot aus dem Steinofen.',           349, 'Backwaren'),
    ('Butter-Croissant',       'Frisches Croissant aus reinem Butterteig.',              129, 'Backwaren'),
    ('Vollmilch 1 L',          'Frische Vollmilch 3,5 % Fett aus der Region.',           119, 'Molkerei'),
    ('Naturjoghurt 500 g',     'Cremiger Naturjoghurt 3,5 % Fett, ohne Zusätze.',         99, 'Molkerei'),
    ('Mineralwasser 6x1 L',    'Natürliches Mineralwasser, spritzig, im Sixpack.',       399, 'Getränke'),
    ('Orangensaft 1 L',        'Direktsaft aus 100 % Orangen, nicht aus Konzentrat.',    249, 'Getränke');
